---

- name: Configure a Linux laptop
  hosts: all

  roles:
    - packages
    - dotfiles
    - keyd
    - alternatives
    - bluez
    - role: thinkpad_bios
      when:
        - ansible_product_version is defined and "thinkpad" in ansible_product_version | lower
