- name: Add keyd APT repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/keyd-team-ppa-noble.gpg] https://ppa.launchpadcontent.net/keyd-team/ppa/ubuntu noble main"
    state: present
    codename: noble
    update_cache: yes

- name: Ensure keyd is installed
  become: true
  ansible.builtin.package:
    name: keyd
    state: present

- name: Get a list of keyd config files to create
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    file_type: file
  register: keyd_files

- name: Deploy all keyd config files
  become: true
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "/etc/keyd/{{ item.path | basename }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ keyd_files.files }}"
  loop_control:
    label: "Creating /etc/keyd/{{ item.path | basename }}"
  notify:
    - Restart keyd
