- name: Deploy dotfiles
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ dotfiles_user }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ dotfiles }}"
  loop_control:
    label: "Creating {{ item.dest }}"

- name: Get GPG key ID from filename
  ansible.builtin.set_fact:
    gpg_key_id: "{{ gpg_key_file | basename | splitext | first }}"

- name: Check if GPG is already in keyring
  ansible.builtin.command:
    cmd: "gpg --list-keys {{ gpg_key_id }}"
  register: gpg_key_check
  failed_when: false
  changed_when: false

- name: Copy GPG key to tmp dir
  ansible.builtin.copy:
    src: "{{ gpg_key_file }}"
    dest: "/tmp/pubkey.asc"
    mode: "0644"
  when: gpg_key_check.rc != 0

- name: Import public GPG key
  ansible.builtin.command:
    cmd: "gpg --import --armor /tmp/pubkey.asc"
  when: gpg_key_check.rc != 0
