[ids]
*

[main]
# Treat capslock as a layer modifier on long key press
# and as escape on short key press
capslock = overload(layer1, esc)

[layer1]
i = up
j = left
k = down
l = right
u = pageup
o = pagedown
s = rightshift
d = leftcontrol
f = leftalt
m = mute
, = volumedown
. = volumeup
